"""
    Big Book API

    The world's book wrapped into a single API.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: mail@bigbookapi.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from com.bigbookapi.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_similar_books(self):
        """Test case for find_similar_books

        Find Similar Books  # noqa: E501
        """
        pass

    def test_get_book_information(self):
        """Test case for get_book_information

        Get Book Information  # noqa: E501
        """
        pass

    def test_search_authors(self):
        """Test case for search_authors

        Search Authors  # noqa: E501
        """
        pass

    def test_search_books(self):
        """Test case for search_books

        Search Books  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
