=begin
#Big Book API

#The world's book wrapped into a single API.

The version of the OpenAPI document: 1.0
Contact: mail@bigbookapi.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

module OpenapiClient
  VERSION = '1.0.0'
end
