=begin
#Big Book API

#Big Book API lets you semantically search over 4 million English books by text, genre, author, ISBN, and more. You can also find books that are similar to each other.

The version of the OpenAPI document: 1.0
Contact: mail@bigbookapi.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

module OpenapiClient
  VERSION = '1.0.0'
end
