#import <Foundation/Foundation.h>
#import <JSONModel/JSONValueTransformer.h>

/**
* Big Book API
* Big Book API lets you semantically search over 4 million English books by text, genre, author, ISBN, and more. You can also find books that are similar to each other.
*
* The version of the OpenAPI document: 1.0
* Contact: mail@bigbookapi.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface JSONValueTransformer (ISO8601)

@end
