--[[
  Big Book API

  Big Book API lets you semantically search over 4 million English books by text, genre, author, ISBN, and more. You can also find books that are similar to each other.

  The version of the OpenAPI document: 1.0
  Contact: mail@bigbookapi.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for bigbookapi.api.default_api
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("default_api", function()
  local bigbookapi_default_api = require "bigbookapi.api.default_api"
  -- unit tests for find_similar_books
  describe("find_similar_books test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for get_book_information
  describe("get_book_information test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for search_authors
  describe("search_authors test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for search_books
  describe("search_books test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
