{-
   Big Book API

   The world's book wrapped into a single API.

   OpenAPI Version: 3.0.0
   Big Book API API version: 1.0
   Contact: mail@bigbookapi.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : BigBook.API
-}

module BigBook.API
  ( module BigBook.API.ApiDefault
  ) where

import BigBook.API.ApiDefault