{-
   Big Book API

   Big Book API lets you semantically search over 4 million English books by text, genre, author, ISBN, and more. You can also find books that are similar to each other.

   OpenAPI Version: 3.0.0
   Big Book API API version: 1.0
   Contact: mail@bigbookapi.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : BigBook.API
-}

module BigBook.API
  ( module BigBook.API.ApiDefault
  ) where

import BigBook.API.ApiDefault