/**
 * Big Book API
 * Big Book API lets you semantically search over 4 million English books by text, genre, author, ISBN, and more. You can also find books that are similar to each other.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@bigbookapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import DefaultApi from './com.bigbookapi/DefaultApi';


/**
* Big_Book_API_lets_you_semantically_search_over_4_million_English_books_by_text_genre_author_ISBN_and_more__You_can_also_find_books_that_are_similar_to_each_other_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var BigBookApi = require('com.bigbookapi.client/index'); // See note below*.
* var xxxSvc = new BigBookApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new BigBookApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['com.bigbookapi.client/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new BigBookApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new BigBookApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module com.bigbookapi.client/index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:com.bigbookapi.client/ApiClient}
     */
    ApiClient,

    /**
    * The DefaultApi service constructor.
    * @property {module:com.bigbookapi.client/com.bigbookapi/DefaultApi}
    */
    DefaultApi
};
